"""add genre to movie

Revision ID: 423e4f189f97
Revises: c35bb9db62a4
Create Date: 2025-11-27 16:41:01.233901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423e4f189f97'
down_revision = 'c35bb9db62a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
